version: "3.4"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
    depends_on:
      - users
      - conferences
      - files
      - grants
    restart: unless-stopped
    ports:
      - "5000:5000"

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
      MONGODB_URI: "$${env.USERS_MONGODB_URI}"
    depends_on:
      - rabbitmq
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - "5001:5001"

  files:
    build:
      context: ./files
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
      MONGODB_URI: "$${env.FILES_MONGODB_URI}"
    depends_on:
      - rabbitmq
      - mongo
      - redis
    volumes:
      - ./files/public:/usr/app/public
    restart: unless-stopped
    ports:
      - "5002:5002"

  conferences:
    build:
      context: ./conferences
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
      MONGODB_URI: "$${env.CONFERENCES_MONGODB_URI}"
    depends_on:
      - rabbitmq
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - "5003:5003"

  grants:
    build:
      context: ./grants
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
      MONGODB_URI: "$${env.GRANTS_MONGODB_URI}"
    depends_on:
      - rabbitmq
      - mongo
    restart: unless-stopped
    ports:
      - "5004:5004"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - gateway
    restart: unless-stopped
    ports:
      - "3000:3000"

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    environment:
      SECRET: "$${env.SECRET}"
      MAIL_HOST: "$${env.MAIL_HOST}"
      MAIL_PORT: "$${env.MAIL_PORT}"
      MAIL_USER: "$${env.MAIL_USER}"
      MAIL_PASSWORD: "$${env.MAIL_PASSWORD}"
      MAIL_FROM: "$${env.MAIL_FROM}"
      CLIENT_APP_URL: "$${env.CLIENT_APP_URL}"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

volumes:
  mongo_data: {}
  mongo_config: {}
