services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
    depends_on:
      - users
      - conferences
      - files
      - grants
    volumes:
      - ./gateway:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "5000:5000"

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
      MONGODB_URI: ${USERS_MONGODB_URI}
      RMQ_URI: ${RMQ_URI}
      RMQ_EXCHANGE: ${RMQ_EXCHANGE}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_healthy
        restart: true
    volumes:
      - ./users:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "5001:5001"

  files:
    build:
      context: ./files
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
      MONGODB_URI: ${FILES_MONGODB_URI}
      RMQ_URI: ${RMQ_URI}
      RMQ_EXCHANGE: ${RMQ_EXCHANGE}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_healthy
        restart: true
    volumes:
      - ./files:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "5002:5002"

  conferences:
    build:
      context: ./conferences
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
      MONGODB_URI: ${CONFERENCES_MONGODB_URI}
      RMQ_URI: ${RMQ_URI}
      RMQ_EXCHANGE: ${RMQ_EXCHANGE}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_healthy
        restart: true
    volumes:
      - ./conferences:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "5003:5003"

  grants:
    build:
      context: ./grants
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
      MONGODB_URI: ${GRANTS_MONGODB_URI}
      RMQ_URI: ${RMQ_URI}
      RMQ_EXCHANGE: ${RMQ_EXCHANGE}
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_healthy
        restart: true
    volumes:
      - ./grants:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "5004:5004"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    depends_on:
      - gateway
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "3000:3000"

  client13:
    build:
      context: ./client13
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - gateway
    volumes:
      - ./client13/:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped
    ports:
      - "3001:3000"

  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
      SECRET: ${SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      RMQ_URI: ${RMQ_URI}
      RMQ_EXCHANGE: ${RMQ_EXCHANGE}
    command: npm run start:dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./mail:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "echo 'PING' | redis-cli -h redis -x"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongo_data: {}
  mongo_config: {}
