query submission($id: ObjectId!) {
  submission(id: $id) {
    id
    name
    abstract
    keywords
    conference {
      id
    }
    section {
      id
      name
    }
    authors {
      name
      email
    }
    updatedAt
    translations {
      language
      name
      abstract
      keywords
    }
  }
}

mutation addSubmission($data: SubmissionInput!) {
  addSubmission(data: $data) {
    id
    name
    abstract
    keywords
    section {
      id
      name
    }
    authors {
      name
      email
    }
    updatedAt
    translations {
      language
      name
      abstract
      keywords
    }
  }
}

mutation updateSubmission($id: ObjectId!, $data: SubmissionInput!) {
  updateSubmission(id: $id, data: $data) {
    id
    name
    abstract
    keywords
    section {
      id
      name
    }
    authors {
      name
      email
    }
    updatedAt
    translations {
      language
      name
      abstract
      keywords
    }
  }
}

mutation deleteSubmission($id: ObjectId!) {
  deleteSubmission(id: $id) {
    id
  }
}

mutation addSubmissionFile($id: ObjectId!, $url: String!) {
  addSubmissionFile(id: $id, url: $url) {
    id
    submissionUrl
  }
}

mutation deleteSubmissionFile($id: ObjectId!, $url: String!) {
  deleteSubmissionFile(id: $id, url: $url) {
    id
    submissionUrl
  }
}
