name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: pull new code
        run: |
          cd /home/weby/Desktop/FlawIS
          git pull
        
      - name: Build and Deploy
        run: sudo docker-compose -f docker-compose.prod.yml up -d --build
