name: Build and Deploy
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy DBs
        env:
          MONGO_CONTAINER_NAME: "flawis-mongo-1"
        run: |
          docker exec $MONGO_CONTAINER_NAME mongo --eval "db.copyDatabase('users', 'users_copy')"
          docker exec $MONGO_CONTAINER_NAME mongo --eval "db.copyDatabase('conferences', 'conferences_copy')"
          docker exec $MONGO_CONTAINER_NAME mongo --eval "db.copyDatabase('grants', 'grants_copy')"
          docker exec $MONGO_CONTAINER_NAME mongo --eval "db.copyDatabase('files', 'files_copy')"

      - name: Copy files to staging
        run: |
          cp -R /home/weby/Desktop/FlawIS/files/public/* /home/weby/Desktop/FlawIS-staging-files

      - name: Build and Deploy
        env:
          SECRET: ${{ secrets.SECRET }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          CLIENT_APP_URL: ${{ secrets.CLIENT_APP_URL }}
        run: |
          whoami
          groups

          docker-compose -f docker-compose.staging.yml up -d --build
