name: Build and Deploy
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Copy DBs
        env:
          MONGO_CONTAINER_NAME: "flawis-mongo-1"
        run: |
          docker exec $MONGO_CONTAINER_NAME mongodump --uri "mongodb://mongo:27017" --archive=/data/users_dump.archive --gzip --db=users
          docker exec $MONGO_CONTAINER_NAME mongorestore --uri "mongodb://mongo:27017" --archive=/data/users_dump.archive --gzip --nsFrom='users.*' --nsTo='users_copy.*'

          docker exec $MONGO_CONTAINER_NAME mongodump --uri "mongodb://mongo:27017" --archive=/data/conferences_dump.archive --gzip --db=conferences
          docker exec $MONGO_CONTAINER_NAME mongorestore --uri "mongodb://mongo:27017" --archive=/data/conferences_dump.archive --gzip --nsFrom='conferences.*' --nsTo='conferences_copy.*'

          docker exec $MONGO_CONTAINER_NAME mongodump --uri "mongodb://mongo:27017" --archive=/data/grants_dump.archive --gzip --db=grants
          docker exec $MONGO_CONTAINER_NAME mongorestore --uri "mongodb://mongo:27017" --archive=/data/grants_dump.archive --gzip --nsFrom='grants.*' --nsTo='grants_copy.*'

          docker exec $MONGO_CONTAINER_NAME mongodump --uri "mongodb://mongo:27017" --archive=/data/files_dump.archive --gzip --db=files
          docker exec $MONGO_CONTAINER_NAME mongorestore --uri "mongodb://mongo:27017" --archive=/data/files_dump.archive --gzip --nsFrom='files.*' --nsTo='files_copy.*'

      - name: Copy files to staging
        run: |
          cp -R /home/weby/Desktop/FlawIS/files/public/* /home/weby/Desktop/FlawIS-staging-files

      - name: Build and Deploy
        env:
          SECRET: ${{ secrets.SECRET }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          CLIENT_APP_URL: ${{ secrets.CLIENT_APP_URL }}
        run: |
          whoami
          groups

          docker-compose -f docker-compose.staging.yml up -d --build
